<?php

use Faker\Generator as Faker;

/*
|--------------------------------------------------------------------------
| Model Factories
|--------------------------------------------------------------------------
|
| This directory should contain each of the model factory definitions for
| your application. Factories provide a convenient way to generate new
| model instances for testing / seeding your application's database.
|
*/

$factory->define(App\Models\Page::class, function (Faker $faker) {

    return [
        'url' => 'bogus',
        'html' => <<<HTML
<html op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?f1GfRfEHDYi45XPIwqNT">
            <link rel="shortcut icon" href="favicon.ico">
          <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
        <title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
          <tr><td bgcolor="#000000"><img src="s.gif" height="5" width="0"></td></tr>
<tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com"><img src="y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="news">Hacker News</a></b>
              <a href="newest">new</a> | <a href="newcomments">comments</a> | <a href="show">show</a> | <a href="ask">ask</a> | <a href="jobs">jobs</a> | <a href="submit">submit</a>            </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                              <a href="login?goto=news">login</a>
                          </span></td>
              </tr></table></td></tr>
<tr style="height:10px"></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
              <tr class='athing' id='18220020'>
      <td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18220020' href='vote?id=18220020&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://ckeditor.com/blog/Lessons-learned-from-creating-a-rich-text-editor-with-real-time-collaboration/" class="storylink">Lessons learned from creating a real-time collaborative rich-text editor</a><span class="sitebit comhead"> (<a href="from?site=ckeditor.com"><span class="sitestr">ckeditor.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18220020">164 points</span> by <a href="user?id=Reinmar" class="hnuser">Reinmar</a> <span class="age"><a href="item?id=18220020">3 hours ago</a></span> <span id="unv_18220020"></span> | <a href="hide?id=18220020&amp;goto=news">hide</a> | <a href="item?id=18220020">16&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18229452'>
      <td align="right" valign="top" class="title"><span class="rank">2.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18229452' href='vote?id=18229452&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://techcrunch.com/2018/10/16/mongodb-switches-up-its-open-source-license/" class="storylink">MongoDB switches up its open source license</a><span class="sitebit comhead"> (<a href="from?site=techcrunch.com"><span class="sitestr">techcrunch.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18229452">122 points</span> by <a href="user?id=zhuxuefeng1994" class="hnuser">zhuxuefeng1994</a> <span class="age"><a href="item?id=18229452">3 hours ago</a></span> <span id="unv_18229452"></span> | <a href="hide?id=18229452&amp;goto=news">hide</a> | <a href="item?id=18229452">139&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18230839'>
      <td align="right" valign="top" class="title"><span class="rank">3.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18230839' href='vote?id=18230839&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://blog.golang.org/appengine-go111" class="storylink">Announcing App Engine’s New Go 1.11 Runtime</a><span class="sitebit comhead"> (<a href="from?site=golang.org"><span class="sitestr">golang.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18230839">43 points</span> by <a href="user?id=SamWhited" class="hnuser">SamWhited</a> <span class="age"><a href="item?id=18230839">48 minutes ago</a></span> <span id="unv_18230839"></span> | <a href="hide?id=18230839&amp;goto=news">hide</a> | <a href="item?id=18230839">12&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18231097'>
      <td align="right" valign="top" class="title"><span class="rank">4.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18231097' href='vote?id=18231097&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://techcrunch.com/2018/10/16/github-launches-actions-its-workflow-automation-tool/" class="storylink" rel="nofollow">GitHub launches Actions, its workflow automation tool</a><span class="sitebit comhead"> (<a href="from?site=techcrunch.com"><span class="sitestr">techcrunch.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18231097">12 points</span> by <a href="user?id=moritzplassnig" class="hnuser">moritzplassnig</a> <span class="age"><a href="item?id=18231097">23 minutes ago</a></span> <span id="unv_18231097"></span> | <a href="hide?id=18231097&amp;goto=news">hide</a> | <a href="item?id=18231097">1&nbsp;comment</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18228627'>
      <td align="right" valign="top" class="title"><span class="rank">5.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18228627' href='vote?id=18228627&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.scientificamerican.com/article/how-exercise-might-clean-the-alzheimers-brain1/" class="storylink">How Exercise Might “Clean” the Alzheimer's Brain</a><span class="sitebit comhead"> (<a href="from?site=scientificamerican.com"><span class="sitestr">scientificamerican.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18228627">261 points</span> by <a href="user?id=extraterra" class="hnuser">extraterra</a> <span class="age"><a href="item?id=18228627">5 hours ago</a></span> <span id="unv_18228627"></span> | <a href="hide?id=18228627&amp;goto=news">hide</a> | <a href="item?id=18228627">127&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18219960'>
      <td align="right" valign="top" class="title"><span class="rank">6.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18219960' href='vote?id=18219960&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://getpolarized.io/" class="storylink">Show HN: Polar – an offline web browser with annotations and tagging</a><span class="sitebit comhead"> (<a href="from?site=getpolarized.io"><span class="sitestr">getpolarized.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18219960">122 points</span> by <a href="user?id=burtonator" class="hnuser">burtonator</a> <span class="age"><a href="item?id=18219960">5 hours ago</a></span> <span id="unv_18219960"></span> | <a href="hide?id=18219960&amp;goto=news">hide</a> | <a href="item?id=18219960">40&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18230226'>
      <td align="right" valign="top" class="title"><span class="rank">7.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18230226' href='vote?id=18230226&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://fermatslibrary.com/s/does-being-bored-make-us-more-creative" class="storylink">Does being bored make us more creative? (2014)</a><span class="sitebit comhead"> (<a href="from?site=fermatslibrary.com"><span class="sitestr">fermatslibrary.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18230226">22 points</span> by <a href="user?id=mgdo" class="hnuser">mgdo</a> <span class="age"><a href="item?id=18230226">1 hour ago</a></span> <span id="unv_18230226"></span> | <a href="hide?id=18230226&amp;goto=news">hide</a> | <a href="item?id=18230226">9&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18220996'>
      <td align="right" valign="top" class="title"><span class="rank">8.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18220996' href='vote?id=18220996&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://docs.google.com/spreadsheets/d/1-UlA4-tslROBDS9IqHalWVztqZo7uxlCeKPQ-8uoFOU/edit" class="storylink">Messenger systems compared by security, privacy, compatibility, and features</a><span class="sitebit comhead"> (<a href="from?site=docs.google.com"><span class="sitestr">docs.google.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18220996">168 points</span> by <a href="user?id=lrvick" class="hnuser">lrvick</a> <span class="age"><a href="item?id=18220996">7 hours ago</a></span> <span id="unv_18220996"></span> | <a href="hide?id=18220996&amp;goto=news">hide</a> | <a href="item?id=18220996">128&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18212182'>
      <td align="right" valign="top" class="title"><span class="rank">9.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18212182' href='vote?id=18212182&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.theguardian.com/business/2017/may/02/where-oil-rigs-go-to-die" class="storylink">Where Oil Rigs Go to Die (2017)</a><span class="sitebit comhead"> (<a href="from?site=theguardian.com"><span class="sitestr">theguardian.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18212182">21 points</span> by <a href="user?id=fredley" class="hnuser">fredley</a> <span class="age"><a href="item?id=18212182">2 hours ago</a></span> <span id="unv_18212182"></span> | <a href="hide?id=18212182&amp;goto=news">hide</a> | <a href="item?id=18212182">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18224227'>
      <td align="right" valign="top" class="title"><span class="rank">10.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18224227' href='vote?id=18224227&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.cnbc.com/2018/10/15/microsoft-co-founder-paul-allen-dies-of-cancer-at-age-65.html" class="storylink">Paul Allen has died</a><span class="sitebit comhead"> (<a href="from?site=cnbc.com"><span class="sitestr">cnbc.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18224227">2768 points</span> by <a href="user?id=coloneltcb" class="hnuser">coloneltcb</a> <span class="age"><a href="item?id=18224227">19 hours ago</a></span> <span id="unv_18224227"></span> | <a href="hide?id=18224227&amp;goto=news">hide</a> | <a href="item?id=18224227">269&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18215168'>
      <td align="right" valign="top" class="title"><span class="rank">11.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18215168' href='vote?id=18215168&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.dropbox.com/s/x83gyclt497fi8t/Ring%20Neighborhoods%20Portal_1.mp4?dl=0" class="storylink">Amazon's Ring Police Portal For Mass Surveillance</a><span class="sitebit comhead"> (<a href="from?site=dropbox.com"><span class="sitestr">dropbox.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18215168">148 points</span> by <a href="user?id=emcarey" class="hnuser">emcarey</a> <span class="age"><a href="item?id=18215168">3 hours ago</a></span> <span id="unv_18215168"></span> | <a href="hide?id=18215168&amp;goto=news">hide</a> | <a href="item?id=18215168">69&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18230769'>
      <td align="right" valign="top" class="title"><span class="rank">12.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18230769' href='vote?id=18230769&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.nytimes.com/2018/10/16/technology/google-android-europe-apps.html" class="storylink">Google to Charge Phone Makers for Android Apps in Europe</a><span class="sitebit comhead"> (<a href="from?site=nytimes.com"><span class="sitestr">nytimes.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18230769">33 points</span> by <a href="user?id=ucaetano" class="hnuser">ucaetano</a> <span class="age"><a href="item?id=18230769">54 minutes ago</a></span> <span id="unv_18230769"></span> | <a href="hide?id=18230769&amp;goto=news">hide</a> | <a href="item?id=18230769">41&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18228750'>
      <td align="right" valign="top" class="title"><span class="rank">13.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18228750' href='vote?id=18228750&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://techcrunch.com/2018/10/16/gartner-picks-digital-ethics-and-privacy-as-a-strategic-trend-for-2019/" class="storylink">Gartner picks digital ethics and privacy as a strategic trend for 2019</a><span class="sitebit comhead"> (<a href="from?site=techcrunch.com"><span class="sitestr">techcrunch.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18228750">45 points</span> by <a href="user?id=RobertSmith" class="hnuser">RobertSmith</a> <span class="age"><a href="item?id=18228750">5 hours ago</a></span> <span id="unv_18228750"></span> | <a href="hide?id=18228750&amp;goto=news">hide</a> | <a href="item?id=18228750">10&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18227029'>
      <td align="right" valign="top" class="title"><span class="rank">14.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18227029' href='vote?id=18227029&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://randomascii.wordpress.com/2018/10/15/making-windows-slower-part-2-process-creation/" class="storylink">Making Windows Slower Part 2: Process Creation</a><span class="sitebit comhead"> (<a href="from?site=randomascii.wordpress.com"><span class="sitestr">randomascii.wordpress.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18227029">137 points</span> by <a href="user?id=nikbackm" class="hnuser">nikbackm</a> <span class="age"><a href="item?id=18227029">11 hours ago</a></span> <span id="unv_18227029"></span> | <a href="hide?id=18227029&amp;goto=news">hide</a> | <a href="item?id=18227029">19&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18229527'>
      <td align="right" valign="top" class="title"><span class="rank">15.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18229527' href='vote?id=18229527&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://github.com/k88hudson/git-flight-rules" class="storylink">Flight rules for Git</a><span class="sitebit comhead"> (<a href="from?site=github.com"><span class="sitestr">github.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18229527">93 points</span> by <a href="user?id=spenrose" class="hnuser">spenrose</a> <span class="age"><a href="item?id=18229527">3 hours ago</a></span> <span id="unv_18229527"></span> | <a href="hide?id=18229527&amp;goto=news">hide</a> | <a href="item?id=18229527">63&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18229776'>
      <td align="right" valign="top" class="title"><span class="rank">16.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18229776' href='vote?id=18229776&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.backblaze.com/blog/2018-hard-drive-failire-rates/" class="storylink">Backblaze Drive Stats: 2018 Q3 Hard Drive Failure Rates</a><span class="sitebit comhead"> (<a href="from?site=backblaze.com"><span class="sitestr">backblaze.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18229776">61 points</span> by <a href="user?id=LaSombra" class="hnuser">LaSombra</a> <span class="age"><a href="item?id=18229776">2 hours ago</a></span> <span id="unv_18229776"></span> | <a href="hide?id=18229776&amp;goto=news">hide</a> | <a href="item?id=18229776">12&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18225929'>
      <td align="right" valign="top" class="title"><span class="rank">17.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18225929' href='vote?id=18225929&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.theatlantic.com/business/archive/2017/09/sears-predicts-amazon/540888/?single_page=true" class="storylink">The History of Sears Predicts Nearly Everything Amazon Is Doing (2017)</a><span class="sitebit comhead"> (<a href="from?site=theatlantic.com"><span class="sitestr">theatlantic.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18225929">195 points</span> by <a href="user?id=kimsk112" class="hnuser">kimsk112</a> <span class="age"><a href="item?id=18225929">15 hours ago</a></span> <span id="unv_18225929"></span> | <a href="hide?id=18225929&amp;goto=news">hide</a> | <a href="item?id=18225929">90&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18223001'>
      <td align="right" valign="top" class="title"><span class="rank">18.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18223001' href='vote?id=18223001&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.the-tls.co.uk/articles/public/measure-of-homer-review/" class="storylink">The extra­ordinary influence of the Iliad and Odyssey</a><span class="sitebit comhead"> (<a href="from?site=the-tls.co.uk"><span class="sitestr">the-tls.co.uk</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18223001">105 points</span> by <a href="user?id=pepys" class="hnuser">pepys</a> <span class="age"><a href="item?id=18223001">13 hours ago</a></span> <span id="unv_18223001"></span> | <a href="hide?id=18223001&amp;goto=news">hide</a> | <a href="item?id=18223001">57&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18227837'>
      <td align="right" valign="top" class="title"><span class="rank">19.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18227837' href='vote?id=18227837&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://github.com/leonardomso/33-js-concepts" class="storylink">Concepts to help developers master JavaScript</a><span class="sitebit comhead"> (<a href="from?site=github.com"><span class="sitestr">github.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18227837">239 points</span> by <a href="user?id=alexgrcs" class="hnuser">alexgrcs</a> <span class="age"><a href="item?id=18227837">8 hours ago</a></span> <span id="unv_18227837"></span> | <a href="hide?id=18227837&amp;goto=news">hide</a> | <a href="item?id=18227837">31&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18208996'>
      <td align="right" valign="top" class="title"><span class="rank">20.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18208996' href='vote?id=18208996&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://torrentfreak.com/tribler-invented-paid-torrent-seeding-over-a-decade-ago-181013/" class="storylink">Tribler Invented 'Paid' Torrent Seeding Over a Decade Ago</a><span class="sitebit comhead"> (<a href="from?site=torrentfreak.com"><span class="sitestr">torrentfreak.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18208996">44 points</span> by <a href="user?id=okket" class="hnuser">okket</a> <span class="age"><a href="item?id=18208996">6 hours ago</a></span> <span id="unv_18208996"></span> | <a href="hide?id=18208996&amp;goto=news">hide</a> | <a href="item?id=18208996">7&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18230932'>
      <td align="right" valign="top" class="title"><span class="rank">21.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18230932' href='vote?id=18230932&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://www.sciencemag.org/news/2017/01/brain-pollution-evidence-builds-dirty-air-causes-alzheimer-s-dementia" class="storylink">Brain pollution: Evidence builds that dirty air causes Alzheimer’s, dementia</a><span class="sitebit comhead"> (<a href="from?site=sciencemag.org"><span class="sitestr">sciencemag.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18230932">9 points</span> by <a href="user?id=dsr12" class="hnuser">dsr12</a> <span class="age"><a href="item?id=18230932">38 minutes ago</a></span> <span id="unv_18230932"></span> | <a href="hide?id=18230932&amp;goto=news">hide</a> | <a href="item?id=18230932">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18225870'>
      <td align="right" valign="top" class="title"><span class="rank">22.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18225870' href='vote?id=18225870&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://twobithistory.org/2018/10/14/lisp.html" class="storylink">How Lisp Became God's Own Programming Language</a><span class="sitebit comhead"> (<a href="from?site=twobithistory.org"><span class="sitestr">twobithistory.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18225870">537 points</span> by <a href="user?id=chwolfe" class="hnuser">chwolfe</a> <span class="age"><a href="item?id=18225870">15 hours ago</a></span> <span id="unv_18225870"></span> | <a href="hide?id=18225870&amp;goto=news">hide</a> | <a href="item?id=18225870">243&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18213022'>
      <td align="right" valign="top" class="title"><span class="rank">23.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18213022' href='vote?id=18213022&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://thestrangeloop.com/2018/tree-sitter---a-new-parsing-system-for-programming-tools.html" class="storylink" rel="nofollow">Tree-sitter – a new parsing system for programming tools [video]</a><span class="sitebit comhead"> (<a href="from?site=thestrangeloop.com"><span class="sitestr">thestrangeloop.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18213022">7 points</span> by <a href="user?id=matt_d" class="hnuser">matt_d</a> <span class="age"><a href="item?id=18213022">1 hour ago</a></span> <span id="unv_18213022"></span> | <a href="hide?id=18213022&amp;goto=news">hide</a> | <a href="item?id=18213022">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18227768'>
      <td align="right" valign="top" class="title"><span class="rank">24.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18227768' href='vote?id=18227768&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://daedtech.com/key-becoming-software-consultant/" class="storylink">To become a software consultant, avoid letting clients pay you for code (2017)</a><span class="sitebit comhead"> (<a href="from?site=daedtech.com"><span class="sitestr">daedtech.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18227768">237 points</span> by <a href="user?id=fagnerbrack" class="hnuser">fagnerbrack</a> <span class="age"><a href="item?id=18227768">8 hours ago</a></span> <span id="unv_18227768"></span> | <a href="hide?id=18227768&amp;goto=news">hide</a> | <a href="item?id=18227768">88&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18228655'>
      <td align="right" valign="top" class="title"><span class="rank">25.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18228655' href='vote?id=18228655&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://www.fast.ai/2018/10/16/aws-datasets/" class="storylink">The new fast.ai research datasets collection, on AWS Open Data</a><span class="sitebit comhead"> (<a href="from?site=fast.ai"><span class="sitestr">fast.ai</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18228655">66 points</span> by <a href="user?id=stablemap" class="hnuser">stablemap</a> <span class="age"><a href="item?id=18228655">5 hours ago</a></span> <span id="unv_18228655"></span> | <a href="hide?id=18228655&amp;goto=news">hide</a> | <a href="item?id=18228655">1&nbsp;comment</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18220246'>
      <td align="right" valign="top" class="title"><span class="rank">26.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18220246' href='vote?id=18220246&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://decryptmedia.com/2018/10/15/augur-ico-prediction-market/" class="storylink">The story of Augur, an Ethereum prediction market</a><span class="sitebit comhead"> (<a href="from?site=decryptmedia.com"><span class="sitestr">decryptmedia.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18220246">86 points</span> by <a href="user?id=ilanhz" class="hnuser">ilanhz</a> <span class="age"><a href="item?id=18220246">11 hours ago</a></span> <span id="unv_18220246"></span> | <a href="hide?id=18220246&amp;goto=news">hide</a> | <a href="item?id=18220246">38&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18229562'>
      <td align="right" valign="top" class="title"><span class="rank">27.</span></td>      <td></td><td class="title"><a href="https://www.givecampus.com/careers#engineering" class="storylink" rel="nofollow">GiveCampus (YC S15) needs engineers who care about education</a><span class="sitebit comhead"> (<a href="from?site=givecampus.com"><span class="sitestr">givecampus.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="age"><a href="item?id=18229562">3 hours ago</a></span> | <a href="hide?id=18229562&amp;goto=news">hide</a>      </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18215141'>
      <td align="right" valign="top" class="title"><span class="rank">28.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18215141' href='vote?id=18215141&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://joshmitteldorf.scienceblog.com/2018/10/14/a-cure-for-alzheimers-yes-a-cure-for-alzheimers/" class="storylink">The Bredesen protocol for treating Alzheimer’s</a><span class="sitebit comhead"> (<a href="from?site=scienceblog.com"><span class="sitestr">scienceblog.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18215141">86 points</span> by <a href="user?id=sjcsjc" class="hnuser">sjcsjc</a> <span class="age"><a href="item?id=18215141">12 hours ago</a></span> <span id="unv_18215141"></span> | <a href="hide?id=18215141&amp;goto=news">hide</a> | <a href="item?id=18215141">22&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18214521'>
      <td align="right" valign="top" class="title"><span class="rank">29.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18214521' href='vote?id=18214521&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.cnn.com/2018/10/09/tech/amazon-sellers-marketplace/index.html" class="storylink">The high-risk, high-reward world of selling random stuff on Amazon</a><span class="sitebit comhead"> (<a href="from?site=cnn.com"><span class="sitestr">cnn.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18214521">105 points</span> by <a href="user?id=prostoalex" class="hnuser">prostoalex</a> <span class="age"><a href="item?id=18214521">13 hours ago</a></span> <span id="unv_18214521"></span> | <a href="hide?id=18214521&amp;goto=news">hide</a> | <a href="item?id=18214521">68&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='18212903'>
      <td align="right" valign="top" class="title"><span class="rank">30.</span></td>      <td valign="top" class="votelinks"><center><a id='up_18212903' href='vote?id=18212903&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://en.wikipedia.org/wiki/Atmospheric_railway" class="storylink">Atmospheric railway</a><span class="sitebit comhead"> (<a href="from?site=wikipedia.org"><span class="sitestr">wikipedia.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_18212903">39 points</span> by <a href="user?id=xiaq" class="hnuser">xiaq</a> <span class="age"><a href="item?id=18212903">8 hours ago</a></span> <span id="unv_18212903"></span> | <a href="hide?id=18212903&amp;goto=news">hide</a> | <a href="item?id=18212903">9&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
            <tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td><td class="title"><a href="news?p=2" class="morelink" rel="nofollow">More</a></td></tr>
  </table>
</td></tr>
<tr><td><img src="s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
        | <a href="newsfaq.html">FAQ</a>
        | <a href="mailto:hn@ycombinator.com">Support</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="security.html">Security</a>
        | <a href="lists">Lists</a>
        | <a href="bookmarklet.html" rel="nofollow">Bookmarklet</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
      </table></center></body><script type='text/javascript' src='hn.js?f1GfRfEHDYi45XPIwqNT'></script>
  </html>
HTML
    ];
});
